### ISSUE TITLE
Uncaught TypeError: Cannot read property 'modelFor' of undefined

### ISSUE THREAD

**Issue by mdgrk** [GetBlimp/ember-parse#10]
Tried to use ember-parse on an app I've been working on for a while, but got this error in the console, referring to session.js line 18.

"Uncaught TypeError: Cannot read property 'modelFor' of undefined"

Thought it might be something to do with dependencies, but even with a "fresh" ember app it doesn't go away. It works on the demo (cloning this repo and running ember server).

Any idea why this is happening?

The part of session.js it's referring to:

    var key = this.get('sessionStoreKey'),
          store = this.container.lookup('store:application'), //store is undefined
          model = store.modelFor('user'),
          adapter = store.adapterFor('application'),
          serializer = store.serializerFor('user');

**Comment by mdgrk** [comment]
Literally have been fighting this all day but just found a fix in JoeyDoom's fork in this commit:

https://github.com/JoeyDoom/ember-parse/commit/16096d871ca544f6d092313fb54758f446dbb4e1

Keep up the good work guys :smile:

**Comment by gcollazo** [comment]
Thanks
