### ISSUE TITLE
Anyway to use this without the CLI ?

### ISSUE THREAD

**Issue by Swizz540** [GetBlimp/ember-parse#14]
Hi!

I am creating a mobile application with Cordova, and I use Ember to do the MVC stuffs.
But I can't use the CLI for doing that job.

Ember and Ember-Data come with a non-CLI version.
Before that day, I used EmberFire (FireBase adapter) which also come with a non-CLI version.

**Comment by gcollazo** [comment]
You can use ember-cli for building Cordova apps. In fact I made this adding specifically for a Cordova app.

You should take a look at ember-cli-cordova on emberaddons.com
