### ISSUE TITLE
[FEATURE REQUEST] Unauthenticated route mixin

### ISSUE THREAD

**Issue by QuantumInformation** [GetBlimp/ember-parse#5]
If a user goes to this route when logged in they should be redirected to index or specified route.

**Comment by gcollazo** [comment]
Already have that. Is just not documented yet.

```js
# routes/myroute.js
import AuthenticatedRouteMixin from 'ember-parse/mixins/authenticated-route-mixin';

export default Ember.Route.extend(AuthenticatedRouteMixin, {
});
```

You can specify a login route on your config.
```js
# config/environment.js

ENV['ember-parse'] = {
  session: {
    loginRoute: 'index'
  }
};
```

**Comment by QuantumInformation** [comment]
Sorry but I meant Un-authenticated :)

**Comment by gcollazo** [comment]
@QuantumInformation not sure what is the purpose of that mixin

**Comment by QuantumInformation** [comment]
Basically this is a route that they should not be able to access if they
are logged them.

Similar to the simple auth mixin.


-- 

Kind regards
Nikos
